### ISSUE TITLE
traceends: incorrect calculation of bytes originated from an endpoint

### ISSUE THREAD

**Issue by safiqul** [LibtraceTeam/libtrace#136]
Traceends is not giving me correct information regarding bytes originated from an endpoint. I have a tracefile where there is only one entry from an endpoint, and as per my calculation the number of bytes originated should not be more than 60 bytes, however traceends prints 10KB (1 packet), which is strange IMO. Could you please check?

**Comment by salcock** [comment]
@jacobvw has contributed a patch that should resolve this issue for you. It has been merged into our development branch and will be included in the next libtrace release.

If you are building libtrace from source, you can also apply the patch yourself as it is a very simple one line fix: 74a59fead9238787648cb18491b679add9587d2f

Let us know if you have any further issues with the `traceends` tool.
