### ISSUE TITLE
Add support for LZO decompression

### ISSUE THREAD

**Issue by salcock** [LibtraceTeam/libtrace#14]
We can write LZO traces but we don't provide any mechanism for reading them back in again. Seeing as it might become more common for people to write LZO traces in future to keep up with high line rates, it would be nice for libtrace to be able to read them natively.

**Comment by mknosher** [comment]
Hello, I'm looking for information on the status of this issue. Is it something that you guys are considering working on any time soon? Generally, is there a roadmap of upcoming features/changes? Thanks!

**Comment by salcock** [comment]
Short answer: probably not in the short term, but if you'd like to have a go at adding this feature yourself then I am more than happy to give you any help that you might need.

Longer answer: at the moment, all libtrace development is driven by whatever features are required for the projects we are working on for our day jobs that happen to use libtrace -- very little libtrace development occurs purely for the sake of libtrace itself, if that makes sense. So there is no planned roadmap specifically for libtrace: it tends to just grow organically. Issues like this one tend to be regarded as "nice to haves" that someone thought of at some point but didn't have the time or the need to implement it.

Right now, I believe none of our main contributors are working on anything that requires LZO decompression, so it's not likely to be written by any of us anytime soon.

Having said that, I don't consider "libtrace developers" to be a closed group  -- anyone who wants to add new features to libtrace, especially those that might have wider appeal,  is welcome to join us and become part of the libtrace team. If that appeals to you (or anyone else reading this), then let me know and I'll get you on board.

One final complication: since the separation of libtrace and libwandio, this is actually more of libwandio issue than a libtrace one these days (although libtrace will need some updating to make use of any new decompression methods in libwandio). But much of the same principles apply to libwandio -- PRs for new features etc will be gladly accepted, but otherwise most improvements will be driven by the developer's downstream needs.
