### ISSUE TITLE
Save output of libprotoident in pcap format

### ISSUE THREAD

**Issue by robtub14** [LibtraceTeam/libtrace#140]
In file lpi_protoident.cc under tools/protoident

Trying to access packet information that is saved in result.

Need to use the information to save result to a pcap file for further processing.

How can you get the output of libprotoident to be saved in a pcap format? Ideally I want to add the packet information output by libprotoident to the actual packet in the form of a flag.

This is the relevant function:

static void per_result(libtrace_t *trace, libtrace_thread_t *sender,
void *global, void *tls, libtrace_result_t *result) {

    char *resultstr;

    if (result->type != RESULT_USER)
            return;

    resultstr = (char *)result->value.ptr;
    printf(resultstr);
    free(resultstr);

}

Thank you for your help.

**Comment by salcock** [comment]
We would need to add per-packet meta-data support to libtrace to support this request.

That would be a nice feature to have, but someone would need to find the time and resources to work on it.
