### ISSUE TITLE
Add read support for pcap-ng format

### ISSUE THREAD

**Issue by salcock** [LibtraceTeam/libtrace#15]
http://www.winpcap.org/ntar/draft/PCAP-DumpFileFormat.html

Starting to come across more and more trace files that use pcap-ng, so we should at least be able to read them.

**Comment by aenertia** [comment]
awesome; has anyone added vxlan decoder yet?

**Comment by isomer** [comment]
I started on one.  I should dig it out and see how far I got.

**Comment by salcock** [comment]
Isomer: you finished it.

https://github.com/wanduow/libtrace/commit/3fc3267f4bfff75debb9cbd9ec0cb25758cafac7

**Comment by Carisbrooke** [comment]
Hi I'm interested in adding support. Did you make any progress, or given me any pointers ?

**Comment by salcock** [comment]
I haven't had time to look into yet. Probably the best way to go about doing this is by extending the code in format_pcapfile.c to add a new format for pcap-ng. That will allow you to reuse any existing pcap format functions that are the same for pcapfile and pcap-ng.

**Comment by salcock** [comment]
It's been a long time coming, but I've finally knocked this one off as of commit 9cdbedb53c7088d7b41ce2130988464b29a03a5c

Write support is still a TODO, though.
