### ISSUE TITLE
Add tracepoint docs (--enable-dtrace)

### ISSUE THREAD

**Issue by rsanger** [LibtraceTeam/libtrace#153]
Adds docs to the wiki for PR #150 and the --enable-dtrace config option.

**Comment by jacobvw** [comment]
Have added some documentation here

https://github.com/LibtraceTeam/libtrace/wiki/User-Space-Tracepoints-%28USDT%29

**Comment by rsanger** [comment]
Great thanks. These tracepoints are really easy to add.
