### ISSUE TITLE
tracertstats should be able to be run against a file in non-tracetime

### ISSUE THREAD

**Issue by salcock** [LibtraceTeam/libtrace#157]
Since switching to using the parallel API, running tracertstats against a trace file will result in it running in trace time. If you have a file covering 60 seconds of actual time (and set an interval of 1 second), then tracertstats will take 60 seconds to run, producing one line of output per second.

Sometimes people don't want that preservation of original trace timing when they're running tracertstats against a file -- they just want to see the per-interval packet counts as fast as possible. Ideally, for non-live inputs this should even be the default behaviour.

While looking into this, we should also verify that the output is consistent when run against the same file multiple times in sequence (e.g. packets shouldn't switch around between intervals) and we should also be better about how we handle intervals with no packets (e.g. make sure we write a line with the timestamp and some zeroes).

**Comment by rsanger** [comment]
Fixed by PR #161
