### ISSUE TITLE
tcp flags misleading

### ISSUE THREAD

**Issue by omarAlkhateebGitHub** [LibtraceTeam/libtrace#160]
Hello everyone,
Thank you for all the effort. I am facing an issue when I want to extract tcp flags using libtrace_tcp_t *tcp = (libtrace_tcp_t *) packet; the SYN flag is always 0 in spite of that it shows me in wireshark that the packets have SYN flag. Moreover, the ACK & RST flags have the value of 1 without any reason. Could you please help me solving this problem?
Thanks in advance.

regards,
Omar

**Comment by rsanger** [comment]
Hi Omar,

Thanks for reporting. This is most likely an endianness or padding issue with the structure.
What system are you running libtrace on and which compiler have you used (if not a system package)?

These structures do all need some extra testing and it is something that we are looking at adding.
I've had a quick look at libtrace_tcp_t * and it seems to be correct on my system; amd64 Ubuntu 16.04 with gcc 5.4.

A solution, for now, is to manually parse out these flags.
CWR = !!(((uint8_t *)tcp)[13] & 0x80)
ECE = !!(((uint8_t *)tcp)[13] & 0x40)
URG = !!(((uint8_t *)tcp)[13] & 0x20)
ACK = !!(((uint8_t *)tcp)[13] & 0x10)
PSH = !!(((uint8_t *)tcp)[13] & 0x08)
RST = !!(((uint8_t *)tcp)[13] & 0x04)
SYN = !!(((uint8_t *)tcp)[13] & 0x02)
FIN = !!(((uint8_t *)tcp)[13] & 0x01)

I would be worth double-checking those results against the flags set in the libtrace_tcp_t structure.

Thanks,
Richard

**Comment by omarAlkhateebGitHub** [comment]
Thanks for your respond. I have ubuntu 20 and I could fix the issue by using tcp = trace_get_tcp( packet). I don't know why this function is working better. Anyway I have the right flags now :).
Thanks for all your effort.
Merry Chrismas
Omar

**Comment by rsanger** [comment]
Oh right, I didn't pick up on this.
The `libtrace_packet_t` structure keeps track of packet metadata as well as a pointer to the actual packet data.
So you cannot cast that structure to a different type and expect to get the correct result.
You should always access the packet headers and payload using the appropriate `trace_get_` function, you can find the list of these here [https://research.wand.net.nz/software/libtrace-docs/html/libtrace_8h.html](https://research.wand.net.nz/software/libtrace-docs/html/libtrace_8h.html)

Merry Christmas 
Richard
