### ISSUE TITLE
Several improper locking bugs(vulnerabilities) found in libtrace

### ISSUE THREAD

**Issue by ycaibb** [LibtraceTeam/libtrace#195]
Hi, developers, thank you for your checking. I found several improper locking in the below codes due to the unreleased locks.

**Comment by ycaibb** [comment]
The lock q->lock is not released before the return.
https://github.com/LibtraceTeam/libtrace/blob/d827850a048405324dcdb39feeee8b3dd01378a6/lib/data-struct/deque.c#L92-L107

**Comment by ycaibb** [comment]
The lock libtrace->libtrace_lock is not released before the return.
https://github.com/LibtraceTeam/libtrace/blob/5350b4a95985969b2dff2f7c677968acb6d29744/lib/trace_parallel.c#L2259-L2265

**Comment by ycaibb** [comment]
The lock b->lock is not released before the return.
https://github.com/LibtraceTeam/libtrace/blob/d827850a048405324dcdb39feeee8b3dd01378a6/lib/data-struct/buckets.c#L190-L211

**Comment by ycaibb** [comment]
The lock q->lock is not released before the return.
https://github.com/LibtraceTeam/libtrace/blob/d827850a048405324dcdb39feeee8b3dd01378a6/lib/data-struct/deque.c#L63-L74

**Comment by ycaibb** [comment]
The lock v->lock is not released before the return.
https://github.com/LibtraceTeam/libtrace/blob/d827850a048405324dcdb39feeee8b3dd01378a6/lib/data-struct/vector.c#L51-L63

**Comment by ycaibb** [comment]
The mutex is not released before the return.
https://github.com/LibtraceTeam/libtrace/blob/5350b4a95985969b2dff2f7c677968acb6d29744/lib/trace.c#L1730-L1744

**Comment by ycaibb** [comment]
The lock trace->libtrace_lock is not released before the thread goes die.
https://github.com/LibtraceTeam/libtrace/blob/5350b4a95985969b2dff2f7c677968acb6d29744/lib/trace_parallel.c#L954-L968

**Comment by ycaibb** [comment]
The lock q->lock is not released before the return.

https://github.com/LibtraceTeam/libtrace/blob/d827850a048405324dcdb39feeee8b3dd01378a6/lib/data-struct/deque.c#L92-L107

**Comment by ycaibb** [comment]
Thank you very much for your checking!

**Comment by salcock** [comment]
Fixed by #196 -- thanks again.
