### ISSUE TITLE
Double unlocking of the lock b->lock

### ISSUE THREAD

**Issue by ycaibb** [LibtraceTeam/libtrace#197]
Dear developers, there is a double unlocking bug in the below code, thank you for your checking.

```
        while (b->packets[b->nextid] != NULL) {
                /* No more packet slots available! */
                pthread_cond_wait(&b->cond, &b->lock);
                pthread_mutex_unlock(&b->lock); // the first time

        }
        b->packets[b->nextid] = b->node;
        b->node->activemembers ++;
        b->node->released[s] = 1;
        b->nextid ++;
        ret = b->nextid - 1;
        pthread_mutex_unlock(&b->lock);  // the second time
```

https://github.com/ycaibb/libtrace/blob/master/lib/data-struct/buckets.c#L161-L172

**Comment by ycaibb** [comment]
Similarly,
https://github.com/LibtraceTeam/libtrace/blob/d827850a048405324dcdb39feeee8b3dd01378a6/lib/data-struct/buckets.c#L127-L142

**Comment by salcock** [comment]
Should now be fixed in the `develop` branch, thank you for bringing this to our attention.
