### ISSUE TITLE
Ubuntu 20.04.3 LTS fails compile due to missing #include <linux/sockios.h>

### ISSUE THREAD

**Issue by milhead2** [LibtraceTeam/libtrace#198]
I had to add this include to a few files, I added it right after the 
#include <linux/can.h>  and can_raw.h if the were in the file.

**Comment by salcock** [comment]
Hello,

Is it possible you've filed this issue against the wrong repository? I don't believe we #include `<linux/can.h>` or `can_raw.h` anywhere in our code.

If I'm wrong, would you be able to tell me which files you needed to add the missing #includes to?
