### ISSUE TITLE
A resource leak

### ISSUE THREAD

**Issue by ryancaicse** [LibtraceTeam/libtrace#200]
`fopen` should be closed in the method misc_report?
https://github.com/LibtraceTeam/libtrace/blob/d827850a048405324dcdb39feeee8b3dd01378a6/tools/tracereport/misc_report.c#L100-L115

**Comment by ryancaicse** [comment]
Could you take a look? Many thanks. @salcock

**Comment by salcock** [comment]
Yes, I think you're right -- not closing probably won't have any major impact as the OS will clean up when the process exits, but it is still a good spot on your part ;)

**Comment by salcock** [comment]
Fixed in the `develop` branch and will be included in the next release.
