### ISSUE TITLE
what's the inputuri in tracepktdump command for dpdk port

### ISSUE THREAD

**Issue by Crazycuo** [LibtraceTeam/libtrace#210]
hi,

i have bind an interface to dpdk.
root@EM-GBDF0H2:usertools$ ./dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
0000:04:00.1 'XtremeScale SFC9250 10/25/40/50/100G Ethernet Controller 0b03' drv=uio_pci_generic unused=sfc,vfio-pci

Network devices using kernel driver
===================================
0000:02:00.0 'NetXtreme BCM5720 2-port Gigabit Ethernet PCIe 165f' if=com1 drv=tg3 unused=vfio-pci,uio_pci_generic *Active*
0000:02:00.1 'NetXtreme BCM5720 2-port Gigabit Ethernet PCIe 165f' if=com2 drv=tg3 unused=vfio-pci,uio_pci_generic 
0000:03:00.0 'NetXtreme BCM5720 2-port Gigabit Ethernet PCIe 165f' if=com3 drv=tg3 unused=vfio-pci,uio_pci_generic 
0000:03:00.1 'NetXtreme BCM5720 2-port Gigabit Ethernet PCIe 165f' if=com4 drv=tg3 unused=vfio-pci,uio_pci_generic 
0000:04:00.0 'XtremeScale SFC9250 10/25/40/50/100G Ethernet Controller 0b03' if=enp4s0f0 drv=sfc unused=vfio-pci,uio_pci_generic *Active*
0000:05:00.0 'XtremeScale SFC9250 10/25/40/50/100G Ethernet Controller 0b03' if=enp5s0f0 drv=sfc unused=vfio-pci,uio_pci_generic *Active*
0000:05:00.1 'XtremeScale SFC9250 10/25/40/50/100G Ethernet Controller 0b03' if=enp5s0f1 drv=sfc unused=vfio-pci,uio_pci_generic *Active*

meanwhile, i also follow "Compiling Libtrace with against a local copy of DPDK" to install libtrace. when i use tracepktdump command to capture packets of 0000:04:00.1. i don't know the inputuri.

i tried like blow, but it doesn't work.
root@EM-GBDF0H2:usertools$ tracepktdump -f "port 8019" -c 10 dpdk:0000:04:00.1
trace_create: Unknown format (dpdk)

Any ideas are appreciated!

**Comment by salcock** [comment]
Hi there,

The good news is that your input URI is correct, but that error suggests that libtrace was not compiled with DPDK support.

Just so I can get an exact picture of what is going on, can you please tell me:
 * what operating system / distribution you are using?
 * is DPDK installed via a package manager or have you built it from source using meson?
 * what version of DPDK are you using?
 * what is the output when you run `./configure` during the libtrace compile process (specifically, the output at the end where it says what build options have been chosen) ?

**Comment by Crazycuo** [comment]
thanks for your replay.

yes. you're right. i reinstall libtrace and the issue is not seen again.
