### ISSUE TITLE
libpacketdump SCTP parsing bug

### ISSUE THREAD

**Issue by alistairking** [LibtraceTeam/libtrace#47]
We ran into a problem when dumping an SCTP packet that is quoted inside an ICMP dest unreach packet where the SCTP parser would blindly believe the quoted chunk length with no regard to the overall packet length passed into the decode function.

We'd get infinite output that looks like this:
```
Mon Apr 17 15:45:29 2017
 Capture: Packet Length: 122/126 Direction Value: -1
 Ethernet: Dest: xx Source: xx Ethertype: 0x0800
 IP: Header Len 20 Ver 4 DSCP 00 ECN 0 Total Length 108
 IP: Id 0 Fragoff 0
 IP: TTL 241 Proto 1 (icmp) Checksum 65523
 IP: Source xx Destination xx
 ICMP: Type: 3 (ICMP Destination Unreachable)
 ICMP: Code: 4 (Fragmentation Required And Dont Fragment Set)
 ICMP: Checksum: 10633
 IP: Header Len 48 Ver 1 DSCP 00 ECN 2 Total Length 37414
 IP: Id 59048 Fragoff 1372 MORE_FRAG DONT_FRAG
 IP: TTL 13 Proto 132 (sctp) Checksum 6909
 IP: Source xx Destination xx
 SCTP: Header Src port 30086 Dst port 17631 Tag 1992624677 Csum 3637884784
 SCTP: Chunk 1 Type INIT ACK Flags 54 Len 51751
 SCTP: Tag 764166009 Credit 2396187391 Outbound 19912 Inbound 38008 TSN 2081719691
 SCTP: Option Unknown type=0 len=0
 SCTP: Option Unknown type=0 len=0
 SCTP: Option Unknown type=0 len=0
 SCTP: Option Unknown type=0 len=0
 SCTP: Option Unknown type=0 len=0
 SCTP: Option Unknown type=0 len=0
 SCTP: Option Unknown type=0 len=0
 SCTP: Option Unknown type=0 len=0
```

Note the line
```
 SCTP: Chunk 1 Type INIT ACK Flags 54 Len 51751
```

That length (51751) is far larger than the actual packet length, but the SCTP parser happily uses it to try and parse the options (https://github.com/LibtraceTeam/libtrace/blob/master/libpacketdump/ip_132.c#L244)

I _quickly_ patched this by preferring the smaller of `vlen` and `len`:
```
diff --git a/libpacketdump/ip_132.c b/libpacketdump/ip_132.c
index 9889161..103917d 100644
--- a/libpacketdump/ip_132.c
+++ b/libpacketdump/ip_132.c
@@ -237,7 +237,12 @@ DLLEXPORT void decode(int link_type UNUSED,const char *packet,unsigned len)
                         ntohs(ack->inbound_streams),
                         ntohl(ack->init_tsn));

-                vlen = chunk->length - (sizeof(struct sctp_init_ack) +
+               if (chunk->length > len) {
+                       vlen = len;
+               } else {
+                       vlen = chunk->length;
+               }
+                vlen = vlen - (sizeof(struct sctp_init_ack) +
                         sizeof(struct sctp_chunk_hdr) +
                         sizeof(struct sctp_common_hdr)
                         );
```
But maybe this isn't the correct fix.
Thoughts?

**Comment by salcock** [comment]
The length fix is definitely a good idea, but I'm looking at that encapsulated packet and seeing a lot of bogus looking values (IP version of 1, IP length of 37414, almost all of the SCTP fields). 

Knowing where you get a lot of your packets from, I'm willing to accept the possibility that libtrace is parsing the packet contents correctly and it is just a really nasty packet. However, I guess we probably should decode the raw packet by hand to make sure that we're not completely messing up the decode in libpacketdump :/

**Comment by alistairking** [comment]
Ah right. I'll see if I can extract the raw packet.
Though, IIRC, at least the IP addresses in the encapsulated IP header looked sane.

**Comment by salcock** [comment]
Resolved (along with a few other SCTP oddities that I found at the same time) in ed3a238f5ae30e9fe5d8bf3122fabb5ae2421969.
