### ISSUE TITLE
 trace_join assertion error in Redhat6

### ISSUE THREAD

**Issue by EaseTheWorld** [LibtraceTeam/libtrace#50]
I downloaded develop branch and run
'examples/skeleton/parallel eth1' and 'Ctrl+C' then error occurs.

lt-parallel: trace_parallel.c:808: hasher_entry: Assertion `trace->state == STATE_FINISHED' failed.
Abort (core dumped)

sometimes another error
Processing packest(eth1): You must call libtrace_start() before trace_read_packet()

Redhat 6.7
eth1 has very low or no traffic
2017-04-21 version(latest commit is f398c61)

**Comment by salcock** [comment]
Thanks for reporting this. I'll take a look at this as soon as I get some free time :)

**Comment by rsanger** [comment]
Sorry for the amount of time this has taken

But I believe I have found and fixed these issues here [fix_assertion_error](https://github.com/LibtraceTeam/libtrace/tree/fix_assertion_error).

If you get a chance to confirm that would be great.

Thanks

**Comment by salcock** [comment]
I'm going to assume this is resolved for now. If not, feel free to reopen this issue.

**Comment by EaseTheWorld** [comment]
Yes. This issue is resolved. Thank you.
