### ISSUE TITLE
Any interest for support for zstd?

### ISSUE THREAD

**Issue by razeh** [LibtraceTeam/libtrace#51]
I'm interested in adding zstd support to libtrace. Before I start:

- 1. Would there be any interest in zstd?
- 2. What would be the best approach for adding zstd support to libtrace?

**Comment by alistairking** [comment]
I'm not really familar with zstd, but it looks interesting, and as far as I'm concerned, the more compression formats we support, the better.

As for how to go about adding support, this is actually something that would be added to wandio (https://github.com/wanduow/wandio), which is the library that libtrace uses for doing IO. 

I'd suggest taking a look at the existing modules (e.g. zlib, bz2), and using one of those as a starting point for adding zstd support. 

The `ior-*` modules implement read support, whereas the `iow-*` modules implement write support. 

In addition to creating `ior-zstd.[ch]` and (optionally) `iow-zstd.[ch]`, you'll need to add hooks to `wandio.c` (e.g., https://github.com/wanduow/wandio/blob/master/lib/wandio.c#L173), and `wandio.h` (e.g., https://github.com/wanduow/wandio/blob/master/lib/wandio.h#L168 and https://github.com/wanduow/wandio/blob/master/lib/wandio.h#L188).

Is that the kind of information you were looking for?
Let me know if you have any other questions, I'm happy to help!

**Comment by razeh** [comment]
Yeap, that's what I'm looking for.
Thanks!

**Comment by razeh** [comment]
ok, I've put in a pull request.

**Comment by salcock** [comment]
This has now been merged into wandio now.
