### ISSUE TITLE
libwandio repository

### ISSUE THREAD

**Issue by euphoria** [LibtraceTeam/libtrace#58]
Does the LibtraceTeam maintain a git repository for libwandio?  It is a dependency that is very closely tied to libtrace, but I can't find an official repository for it, or if any development on wandio has occurred in the last 2 years.

**Comment by salcock** [comment]
Hi,

The official wandio repository is at https://github.com/wanduow/wandio

**Comment by euphoria** [comment]
Thank you.  It might be nice if that were more clear, I could find https://github.com/alistairking/wandio but not the repository you linked.  I am pleasantly surprised to notice that some changes I wanted to make to libwandio are already included in the `wanduow` version.
