### ISSUE TITLE
tracesplit jump-to-IP-header mode outputs corrupt packets after the first one

### ISSUE THREAD

**Issue by antcodd** [LibtraceTeam/libtrace#60]
In tracesplit jump-to-IP-header mode, due to pointer updating and stale caching the reader always return TRACE_TYPE_NONE after the first packet instead of the real linktype causing incorrect conversion (or lack thereof as every packet is effectively treated as if it is already raw IP).

It appears that tracesplit jump updates the packet pointer to a new generated IPv4 output one, then the next libtrace_get_packet() call for some unknown reason checks the libtrace_t is the same in the packet structure before clearing out the old data. Because the new IPv4 packet has a new fake dummy trace_t attached to it the stale cache linktype remains and gets used for the input packet.

I don't see why tracesplit destroys the original input packet buffer it would normally re-use either, it should probably destroy the temporary one and continue using the real input packet; nor why per_packet passes in a libtrace_packet_t**.

**Comment by salcock** [comment]
Fixed as of d97dee927293245a6ca086f7c6e33c29c6916fe4
