### ISSUE TITLE
tracereplay/trace_construct_packet blindly constructs packets with invalid DLT

### ISSUE THREAD

**Issue by antcodd** [LibtraceTeam/libtrace#61]
If the supplied linktype does not have a corresponding DLT, trace_construct_packet() just barrels on with a DLT of -1, leading to an RT type of TRACE_RT_DATA_DLT-1 without error and blindly copying in whatever header and payload was in the packet without any conversion as if it was PCAP. tracereplay then dies later on when l3 conversion attempts to convert RT TRACE_RT_DATA_DLT-1=1999 to a sensible linktype.

Workaround: use tracesplit/traceconvert instead.

e.g.
```
$ tracereplay erf_meta_example_pkts.erf pcap:erf_meta_example_pkts_libtrace.pcap
Error: RT type 1999 cannot be converted to a pcap DLT
tracereplay: linktypes.c:162: rt_to_pcap_linktype: Assertion `false' failed.
Aborted (core dumped)
```

**Comment by salcock** [comment]
477165c0ac03aac4d368bf3569bbc0936f993130 should help address this issue.
