### ISSUE TITLE
trace_pstop doesn't end for pcapint

### ISSUE THREAD

**Issue by EaseTheWorld** [LibtraceTeam/libtrace#69]
I'm using libtrace develop 6d17620 on centos 7.0.
When I run 'tracestats pcapint:eno1' and press ctrl+c,
program doesn't end.
It was hanging at first pthread_mutex_lock(&libtrace->libtrace_lock) in trace_ppause().
int:eno1, ring:eno1 works well, though.

**Comment by rsanger** [comment]
Thanks for the report

I've added a fix to the next release candidate here c95ef4ad, in branch rc-4.0.4 .
We are going to do a new stable release soon, which will include this fix.

Sorry for the time it has taken to fix this.
Let me know if this has not fixed your problem.

**Comment by EaseTheWorld** [comment]
Fixed in 4.0.4. Thank you.
Tested in RHEL 7.4
