### ISSUE TITLE
trace_init() is not thread-safe

### ISSUE THREAD

**Issue by salcock** [LibtraceTeam/libtrace#80]
If you have a multi-threaded program where two threads both attempt to create a trace (alive or dead) at the same time, it is possible for a race condition to occur on the formats_list variable. This usually results in an assertion failure `(f->next == NULL)` in `register_format()`.

It might be that we need to push the responsibility for calling `trace_init()` onto the user directly and hope that they call it in a sensible place. Another option might be to have one format list per trace object; this is a bit wasteful but we could perhaps mitigate this somewhat by only adding formats that are being actively used.

Note that conventional parallel libtrace programs are not affected by this issue, since they should always be creating a trace object in their main thread only, so there shouldn't be any opportunity for a race.

**Comment by rsanger** [comment]
We could make this a constructor then it would be run once when the library is loaded before main() is called in the user's code. For both gcc and clang this should be as simple as adding `__attribute__((constructor))` to trace_init().

We would need to test with all other systems/compilers to check that this works correctly.

**Comment by salcock** [comment]
Fixed by 0bb8d49.
