### ISSUE TITLE
build fail when with wandio dir and with-dpdk configure

### ISSUE THREAD

**Issue by EaseTheWorld** [LibtraceTeam/libtrace#86]
I build wandio 4.0.0 locally and try to build libtrace like this

$ export WANDIO_DIR=/my/wandio/build_dir
$ ./configure --without-ncurses CFLAGS="-L${WANDIO_DIR}/.libs -I${WANDIO_DIR}"  LDFLAGS="-L${WANDIO_DIR}/.libs" --with-dpdk
then configure succeeded but make failed.
  CXXLD libtrace.la
/usr/bin/ld: cannot find -lwandio

if I don't use --with-dpdk, there's no problem.
Any idea? or do I have to make install wandio to /usr/lib64

tested with libtrace 4.0.4, 4.0.5 on RHEL7

**Comment by salcock** [comment]
My first guess would be that something in the magic we use to make DPDK work is clobbering your CFLAGS and/or LDFLAGS.

What does the output of make look like if you run:

    make V=1

**Comment by EaseTheWorld** [comment]
Your guess seems right.
my CFLAGS is in the 'libtool: compile: ...' part but
my LDFLAGS is not in the 'libtool: link: ...' part.
dpdk lib is there instead.

**Comment by rsanger** [comment]
Thanks for the report

Yes, we were accidentally overwriting LDFLAGS when DPDK was enabled.
I have made a fix here https://github.com/LibtraceTeam/libtrace/tree/fix86

Let me know if that solves the problem

**Comment by EaseTheWorld** [comment]
Yes, it works. thank you.

**Comment by EaseTheWorld** [comment]
By the way, how about refer libwandio(and even dpdk) as git submodule? It will resolve version unmatch issue.

**Comment by salcock** [comment]
Fixed by 5964f5255bd8b8a328192fc674eeec3b401262d1 -- thanks Richard.
