### ISSUE TITLE
trace_config() leaks memory (linux, bpf)

### ISSUE THREAD

**Issue by mschiffm** [LibtraceTeam/libtrace#87]
[the following was found on Debian Linux (Stretch)] Configuring a bpf filter results in a situation where the heap memory allocated for filter is orphaned inside the library and not accessible to be freed by the API. An excerpt from a valgrind session showing the call-chain is below:
```
==12792== 488 bytes in 2 blocks are definitely lost in loss record 1 of 1
==12792==    at 0x4C2DBC5: calloc (vg_replace_malloc.c:711)
==12792==    by 0x6479ED1: ??? (in /usr/lib/x86_64-linux-gnu/libpcap.so.1.8.1)
==12792==    by 0x646D0E2: pcap_compile (in /usr/lib/x86_64-linux-gnu/libpcap.so.1.8.1)
==12792==    by 0x586E150: linuxnative_configure_bpf (format_linux_common.c:104)
==12792==    by 0x586E150: linuxcommon_config_input (format_linux_common.c:150)
==12792==    by 0x58605A0: trace_config (trace.c:597)
...
```
This is easy to reproduce via a few small modifications to the example program “stats”:

1. Remove the infinite loop and run `trace_read_packet()` manually a handful of times
1. Add the missing call to `trace_destroy_filter()` near the end of the program.

Run with something like `$ sudo ./stats --filter tcp ring:enp2s0f1` under valgrind with `--leak-check=full` to see something similar to above.

The leak is due to the fact that [libtrace creates a local copy of the filter structure ](https://github.com/LibtraceTeam/libtrace/blob/master/lib/format_linux_common.c#L73-L75), configures that and then stores it internally in the opaque `libtrace_t` object (the internals of which are not directly accessible to the API). The end-user is instead left with the husk of what “filter” was before the copy — a dynamically-allocated sparely populated structure ([created by `trace_create_filter()`](https://github.com/LibtraceTeam/libtrace/blob/master/lib/trace.c#L1488-L1504) (aside: when allocated, this should be `calloc()`’d or `memset()` to zero at inception because it currently contains a few uninitialized members). Calling [`trace_destroy_filter()`](https://github.com/LibtraceTeam/libtrace/blob/master/lib/trace.c#L1506-L1520) using the filter created in `trace_create_filter()` will free `filter->filterstring`, but since `filter->flag == 0`, `pcap_freecode()` won't be called to release the memory allocated by `pcap_compile()` — but even if it did, it would be passing in the wrong filter structure (the one that was user-accessible, not the internal one held by the library). The result is that libtrace holds onto the memory for filter indefinitely. To fix, all of this could subsumed inside the library. 

Special thanks to @shw700 for the second set of eyes.

**Comment by salcock** [comment]
Resolved via #89
