### ISSUE TITLE
NULL ptr deference in pcapfile

### ISSUE THREAD

**Issue by isomer** [LibtraceTeam/libtrace#90]
During fuzzing libtrace, I discovered an invalid trace:

#0  pcapfile_get_wire_length (packet=0xf7ef50) at format_pcapfile.c:629
        sll = 0x0
        pcapptr = 0xf7f020
#1  0x00007f781033bc41 in trace_get_wire_length (packet=<optimized out>) at trace.c:1371
#2  trace_get_packet_buffer (packet=0xf7ef50, linktype=<optimized out>, remaining=0x7ffd7aa7cf84) at trace.c:1149
#3  0x00007f781038f2e6 in trace_get_layer2 (packet=0xf7ef50, linktype=0x7ffd7aa7cf24, remaining=0x7ffd7aa7cf84)
    at protocols_l2.c:457
#4  0x00007f7810392d38 in trace_get_layer3 (packet=0xf7ef50, ethertype=0x7ffd7aa7cf58, remaining=0x7ffd7aa7cf84)
    at protocols_l3.c:244
        linktype = TRACE_TYPE_LINUX_SLL
#5  0x00007f781039705c in trace_get_transport (packet=0xf7ef50, proto=0x7ffd7aa7cf83 "", remaining=0x7ffd7aa7cf84)
    at protocols_transport.c:198
        dummy_proto = 16 '\020'
        ethertype = 37728
#6  0x00007f78103973f0 in trace_get_tcp (packet=0x71) at protocols_transport.c:237
        rem = 0
        proto = 0 '\000'
#7  0x0000000000401378 in main (argc=<optimized out>, argv=<optimized out>) at test-fuzz-format.c:12
        trace = 0xf7de70
        pkt = 0xf7ef50

This appears to that the packet is truncated, so packet->payload is NULL, then when we try and read the SLL header we crash with a sigsegv.

If packet->payload is NULL, then the capture length should be 0 (and shouldn't dereference a NULL pointer in the process).

I've attached two traces that show this issue.

**Comment by isomer** [comment]
Okay, I thought I had attached them, but they're missing now.  Here they are: [crash1.tar.gz](https://github.com/LibtraceTeam/libtrace/files/2752747/crash1.tar.gz)

**Comment by salcock** [comment]
Fixed as of 6b7a958e726f14fedf2755286e27775dcaac5908
