### ISSUE TITLE
trace_get_payload_from_layer2's v4 vs v6 guess has multiple bugs

### ISSUE THREAD

**Issue by isomer** [LibtraceTeam/libtrace#91]
case TRACE_TYPE_NONE:
                        if ((*(char*)link&0xF0) == 0x40)
                                *ethertype=TRACE_ETHERTYPE_IP;   /* IPv4 */
                        else if ((*(char*)link&0xF0) == 0x60)
                                *ethertype=TRACE_ETHERTYPE_IPV6; /* IPv6 */
                        return link; /* I love the simplicity */

This has a few problems:

* link might be NULL, if the layer2 header is missing, or corrupt.
* It doesn't check *remaining has at least 1 byte remaining. 
* if the first byte doesn't have 0x40 or 0x60 as the upper nibble, then it will not set the ethertype, and return.   It should probably just return 0. 

Very similar problems happen for TRACE_TYPE_OPENBSD_LOOP.

I've attached some crashes demonstrating the NULL pointer dereference problem that can be used in a test case: 
[crash2.tar.gz](https://github.com/LibtraceTeam/libtrace/files/2752754/crash2.tar.gz)

**Comment by salcock** [comment]
Fixed as of 385678bdd1007864e8a27e0409fd4b628f571b3f
