### ISSUE TITLE
erf format crashes on corrupted/truncated packets

### ISSUE THREAD

**Issue by isomer** [LibtraceTeam/libtrace#92]
There are multiple reasons that `packet->payload` might be NULL for an erf packet.  The obvious one is:

        if (erfptr->flags.rxerror == 1) {
                packet->payload = NULL;
        }

But there may be other reasons.  erf_get_link_type unconditionally deferences `packet->payload`:

                /* Sigh, lets start wildly guessing */
                if (((char*)packet->payload)[4]==0x45)
                        return TRACE_TYPE_PPP;

This should check that `packet->payload` is not NULL, and that there are at least 5 bytes in the packet.

Here's some traces that show the problem:
[crash3.tar.gz](https://github.com/LibtraceTeam/libtrace/files/2752772/crash3.tar.gz)

**Comment by salcock** [comment]
Fixed following commits e0d922a6372a856e4c2f2de2605d3773abfbf1c3 and 2d16fc7a8bbf48034cf8b5c6ca1258b1d7396af4
