### ISSUE TITLE
trace_get_layer2 doesn't handle trace_get_packet_buffer() returning NULL properly.

### ISSUE THREAD

**Issue by isomer** [LibtraceTeam/libtrace#93]
`trace_get_packet_buffer()` can return NULL, in some situations (eg metadata only packets), then `trace_get_layer2()` will return NULL.  But if it's a normal packet linktype, but there is no packet buffer (eg, because of a receive error, or a truncated packet etc), then it will call `trace_get_payload_from_meta()` on the NULL pointer, which will immediately `assert()` since asking for a payload from NULL is meaningless.

It should, instead, probably check if the return from `trace_get_packet_buffer()` is NULL, and then just return ourselves to clean things up.

Here's some example traces for tests: 
[crash4.tar.gz](https://github.com/LibtraceTeam/libtrace/files/2752781/crash4.tar.gz)

**Comment by salcock** [comment]
Fixed as of 2f9b6097189a1da198edb09e2448709f9a353f46
