### ISSUE TITLE
trace_get_wire_length() requires packets are smaller than necessary.

### ISSUE THREAD

**Issue by isomer** [LibtraceTeam/libtrace#94]
`trace_get_wire_length()` has an assert that the returned value must be less than LIBTRACE_PACKET_BUFSIZE.

This is an overzealous assert, a maximum sized ethernet packet, can have 4 bytes of FCS added, pushing it over `LIBTRACE_PACKET_BUFSIZE`, and triggering the assert.

`trace_get_wire_length()` will never be written into a packet buffer, so it doesn't need to be safety checked to make sure it never exceeds that size.

Fix: Just delete the assert.

**Comment by salcock** [comment]
Fixed in commits 6b7a958e726f14fedf2755286e27775dcaac5908 and d0941cc6cd389886158e191556c851d87348fb24
