### ISSUE TITLE
libtrace should have clang-format-* run before the next release.

### ISSUE THREAD

**Issue by isomer** [LibtraceTeam/libtrace#96]
libtrace's formatting is relatively inconsistent, mostly because I've set some relatively bad examples in my naive younger years... We should fix that.

We should come up with a style we like, then run clang-format-* over the entire libtrace code base, to make it consistent, and much easier to read.

We should do this as the last thing just before a release, to try and minimise the amount of merge conflicts from outstanding changes.

**Comment by salcock** [comment]
Will probably try to do this once Jacob finishes up working on libtrace, so as not to cause issues with the work he's doing at the moment.
